/* 
This script is property of Catalyst Studios for use in the modpack Little Bit Large. It is under the All Rights Reserved license.
It cannot be used or modified outside of Catalyst Studios without explicit permission from Catalyst Studios.
*/
MMREvents.machines(catalyst => {
    /**
     * Creates a machine with the given ResourceLocation (namespace:machine) equivalent to the json -> datapackNamespace:jsonName
     */
    catalyst.create("mmr:advanced_multismelter")
        .color('#FF5E0000')
        .name('Advanced MultiSmelter')
        .structure(
            MMRStructureBuilder.create()
            .pattern([
            ["aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abiiibbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbffffffffgfffffffebbbbbba","abbbbbbdbbbbbbghgbbbbbbebbbbbba","abbbbbbdbffffffgfffffebebbbbbba","abbbbbbdbdbbbbbabbbbbebebbbbbba","abbbbbbdbdbbbbbabbbbbebebbbbbba","abbbbbbdbdccccccccccccbebbbbbba","abbbbbbdbbbbbbbabbbbbbbebbbbbba","abbbbbbdccccccccccccccccbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","abbbbbbbbbbbbbbabbbbbbbbbbbbbba","aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"],
            ["               a               "," bbbbb                         "," b   b                         "," bxxxb                         "," bxxxb                         "," bxxxb        k k              "," bdbdb         w               ","  d d         w w         k k  ","  d d          w     vvv k   k ","  d dccvvv    k k    vvv       ","  d d  vvv blllllllb vvv k   k ","  d dccvvv tuuvvvuut      k k  ","           tuuvvvuut           ","           tuuvvvuut           ","       pbp bslqbqlsb           ","      pbbbp r bqb r k      k   ","       pbp    qbq              ","        p   k       k    k     ","                               ","                               ","               p               "," nnn   nnn    pbp        k k   "," nnn   nnn   pbbbp             "," nnn   nnn    pbp              ","               p               ","                  lll    k k   ","                 loool  k   k  "," nnn   nnn       loool         "," nnn   nnn       loool  k   k  "," nnn   nnn        lll    k k   ","                               "],
            ["               m               ","                               "," k   k                         ","                               ","                               ","              vvv              "," k   k       vvvvv             ","             vvvvv        k k  ","             vvvvv   AAA k   k ","     xxx      vvv    AAA       ","     xxx   blllllllb xAx k   k ","     xxx   tuuxxxuut      k k  ","           tuuxxxuut           ","           tuuxxxuut           ","           bllqbqllb           ","        k   r bqb r k      k   ","              qbq              ","            k       k    k     ","                               ","                               ","                               "," yyy   yyy               k k   "," yyy   yyy     k               "," yyy   yyy                     ","                               ","                  lll    k k   ","                 lo ol  k   k  "," yyy   yyy       loool         "," yyy   yyy       loo l  k   k  "," yyy   yyy        lll    k k   ","                               "],
            ["                               ","                               "," k   k                         ","  CCC                          ","  CCC                          ","  CCC         vvv              "," k   k       vBBBv             ","             vBBBv        k k  ","             vBBBv       k   k ","              vvv              ","           blllllllb     k   k ","           tuuuuuuut      k k  ","           tuuuuuuut           ","           tuuuuuuut           ","           bllqbqllb           ","        k   r bqb r k      k   ","              qbq              ","            k       k    k     ","                               ","                               ","                               "," yyy   yyy               k k   "," yyy   yyy     k               "," yyy   yyy                     ","                               ","                  lll    k k   ","                 l   l  k   k  "," yyy   yyy       loo l         "," yyy   yyy       l o l  k   k  "," yyy   yyy        lll    k k   ","                               "],
            ["                               ","                               "," k   k                         ","  bbb                          ","  bbb                          ","  bbb                          "," k   k                         ","                          b b  ","               I         bbbbb ","                          b b  ","           bbbbbbbbb     bbbbb ","           blHlHlHlb      b b  ","           blHlHlHlb           ","           blHlHlHlb           ","           bbbqbqbbb           ","        k   r bqb rGbGrrrrGb   ","            E qbq          D   ","            bFrrrrrFbFrrFb r   ","                         E r   ","                         r r   ","                         E D   "," yyy   yyy               b b   "," yyy   yyy     k         E D   "," yyy   yyy               r r   ","                         r D   ","                  lll    k b   ","                 l   l  k  Dk  "," yyy   yyy       l o l     r   "," yyy   yyy       l   l  k   k  "," yyy   yyy        lll    k k   ","                               "],
            ["                               ","                               "," k   k                         ","  J J                          ","                               ","  J J                          "," k   k                         ","                          k k  ","               I         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                  bbb    bbb   ","                 bbbbb  bbbbb  ","                 bbbbb  bbbsb  ","                 bbbbb  bbbbb  ","                  bbb    bbb   ","                               "],
            ["                               ","                               "," bb bb                         "," bbbbb                         ","  bbb                          "," bbbbb                         "," bb bb                         ","                          k k  ","               I         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                         lll   ","                        luuul  ","                        luKul  ","                        luuul  ","                         lll   ","                               "],
            ["                               ","                               ","                               ","                               ","                               ","                               ","                               ","                          k k  ","               I         k   k ","                               ","                         k   k ","                          k k  ","                               ","                               ","              qbq              ","        k     bqb              ","              qbq              ","                               ","                               ","                               ","                               ","                               ","               k               ","                               ","                         r     ","                         lll   ","                        luuul  ","                        luKul  ","                        luuul  ","                         lll   ","                               "],
            ["                          MMM  ","                         MMMMM ","                         MMMMM ","                         MMMMM ","                          MMM  ","                               ","                               ","                          b b  ","               I         bbbbb ","                          b    ","                         bbbbb ","                          b b  ","                               ","        L                      ","       LbL    qbq              ","      LbbbL   bqb              ","       LbL    qbq              ","        L                      ","                               ","                               ","               L               ","              LbL              ","             LbbbL             ","              LbL              ","               L         r     ","                         lll   ","                        luuul  ","                        luKul  ","                        luuul  ","                         lll   ","                               "],
            ["                          MMM  ","                         MNiNM ","                         MNNNM ","                         MiNiM ","                          MMM  ","                               ","                               ","                          k k  ","               I         k   k ","        lq                     ","        llq              k   k ","       llqlq              k k  ","       llqll                   ","      llqll                    ","      llqll   qbq              ","      qqqqq   bqb              ","      llqll   qbq              ","      llqll                    ","       llqll                   ","       llqlql     lq           ","        llqllllqllllq          ","        lqlqqllqllqqlq         ","         llllqqqqqllll         ","           llllqllll           ","             llqll       r     ","                         lll   ","                        luuul  ","                        luKul  ","                        luuul  ","                         lll   ","                               "],
            ["                          M M  ","                           N   ","                          iNN  ","                           N   ","                          M M  ","                               ","                               ","                          k k  ","       lq      I         k   k ","       lot                     ","      lloot              k   k ","      loooot              k k  ","      loooooq                  ","     loooool                   "," M   loooool  qbq              "," MM  qoooooq  bqb              "," M   loooool  qbq              ","     loooool                   ","      loooooq     q            ","      loooooollqllot           ","      lloooooooooooot          ","       looooooooooooot         ","       lqoooooooooooooq        ","        lllooooooooolll        ","          lllooooolll    r     ","             llqll       bbb   ","                        bbbbb  ","                        bsbbb  ","               M        bbbbb  ","              MMM        bbb   ","                               "],
            ["                               ","                          M M  ","                           N   ","                          M M  ","                               ","                               ","                               ","       q                  k k  ","      q t      I         k   k ","      q  t                     ","     q    t              k   k ","     q     t              k k  ","     q      tlqqq              "," M  q       lqbqbq             ","    q   AA  qbbqbbq  vv        "," OO q  AAA  qqqqqqq  vvv       ","    q   AA  qbbqbbq  vv        "," M  q       lqbqbq             ","     q       lqqqlt            ","     q             t           ","     q              t          ","      q       vvv    t         ","      q       vvv     t        ","       q       A       q       ","        qq           qq  r     ","          qqq     qqq    r     ","             qqqqq       r     ","                         r     ","               O               ","             M O M             ","                               "],
            ["                               ","                               ","                          MMM  ","                               ","                               ","                               ","                               ","       q                  b b  ","      l t     AIA        bbbbb ","      l  t     A          b b  ","     l    t    A         bbbbb ","     l     t              b b  "," M   l      t                  ","    q   AA    bqb    vv        ","    l  ABBA  b   b  vNNv       ","    l ABBBA  q q q  vNNNv      ","    l  ABBA  b   b  vNNv       ","    q   AA    bqb    vv        "," M   l            t            ","     l             t           ","     l        vvv   t          ","      l      vNBBv   t         ","      l      vBNNv    t        ","       q      ANA      q       ","        ll     A     ll        ","          lll     lll          ","             qlllq             ","                               ","                               ","            M     M            ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t     AWA        k   k ","      l  t    ABA              ","     l    t   ABA        k   k ","     l     t   A          k k  "," MM  q      t                  "," VV q   AA    ttt    vv        ","    l  ABBA  t   t  vNNv       "," UU S ABBBA  t q t  vNiiv      ","    l  ABBA  t   t  viNv       "," TT q   AA    ttt    vv        "," MM  q            t            ","     l             t           ","     l        vvv   t          ","      l      vBNiv   t         ","      l      ANBBA    t        ","       q      AiA      q       ","        ll     A     ll        ","          llq     qll          ","             qlSlq             ","                               ","            MR Q PM            ","            MR Q PM            ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t    A   A       k   k ","      l  t  MA   AM            ","     l    t MA   AM      k   k ","     l     t MAAAM        k k  "," M   l   MM t MMM   MM         ","    q   AA M  tMt  M vv        ","    l AA  A Mt M tM v  vv      ","    l     A MMMMMMM v          ","    l AA  A Mt M tM v  vv      ","    q   AA M  tMt  M vv        "," M   l   MM   MMM t MM         ","     l       M   M t           ","     l      M vvv M t          ","      l     Mv   vM  t         ","      l      v   v    t        ","       q      A A      q       ","        ll    A A    ll        ","          lll     lll          ","             qlllq             ","                               ","                               ","            M     M            ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","       q                  k k  ","      l t    A   A       k   k ","      l  t   A   A             ","     l    t  A   A       k   k ","     l     t  AAA         k k  ","     l      t                  "," M  q         ttt              ","    l        t   t             "," YY l        t   t             ","    l        t   t             "," M  q         ttt              ","     l            t            ","     l             t           ","     l              t          ","      l              t         ","      l               t        ","       q               q       ","        ll           ll        ","          lll     lll          ","             qlllq             ","                               ","               Y               ","             M Y M             ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","       q                  b b  ","      q t     AAA        bbbbb ","      q  t    AAA         bbb  ","     q    t   AAA        bbbbb ","     q     t              b b  ","     q      t qqq              ","    q        qbqbq             "," M  q       qbbqbbq            "," MM q       qqqqqqq            "," M  q       qbbqbbq            ","    q        qbqbq             ","     q        qqq t            ","     q             t           ","     q              t          ","      q              t         ","      q               t        ","       q               q       ","        qq           qq        ","          qqq     qqq          ","             qqqqq             ","                               ","               M               ","              MMM              ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","                          MMM  ","       lq                MMMMM ","       l t               MMMMM ","      ll  t              MMMMM ","      l    t              MMM  ","      l     q                  ","     l     ll                  ","     l     l                   ","     q     q              NNN  ","     l     l              NNN  ","     l     ll                  ","      l     ql   lq            ","      l      llqll t           ","      ll            t          ","       l             t         ","       lq             q        ","        lll         lll        ","          lll     lll          ","             llqll             ","                               ","                               ","                               ","                               ","                               "],
            ["                               ","                               ","                          X X  ","                               ","                               ","                               ","                               ","                               ","                         MZMZM ","        lq                     ","        llq              MZMZM ","       llqlq                   ","       llqll                   ","      llqll                    ","      llqll                    ","      qqqqq               bbb  ","      llqll               NNN  ","      llqll               NNN  ","       llqll                   ","       llqlql     lq           ","        llqllllqllllq          ","        lqlqqllqllqqlq         ","         llllqqqqqllll         ","           llllqllll           ","             llqll             ","                               ","                               ","                               ","                               ","                               ","                               "],
            ["                               ","                               ","                          bbb  ","                          j j  ","                          j j  ","                          j j  ","                          j j  ","                          j j  ","                         MjMjM ","                          j j  ","                         MjMjM ","                          j j  ","                          j j  ","                          j j  ","                          j j  ","                          bbb  ","                          NNN  ","                          NNN  ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               "],
            ["                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                          MMM  ","                               ","                          MMM  ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               ","                               "]])
            .keys({
              "a":[
                    "modular_machinery_reborn:casing_reinforced",
                    '#modular_machinery_reborn:itembus',
                    '#modular_machinery_reborn:energyhatch'
                ],
              "b":["create_new_age:reactor_casing"],
              "c":["mob_grinding_utils:entity_conveyor[facing=north]"],
              "d":["mob_grinding_utils:entity_conveyor[facing=east]"],
              "e":["mob_grinding_utils:entity_conveyor[facing=west]"],
              "f":["mob_grinding_utils:entity_conveyor[facing=south]"],
              "g":["minecraft:piston[extended=true+facing=up]"],
              "h":["minecraft:redstone_block"],
              "i":["minecraft:coal_block"],
              "k":["create:metal_girder"],
              "l":["create_new_age:reactor_glass"],
              "n":["mekanism:induction_casing"],
              "o":["create_new_age:solid_corium"],
              "p":["minecraft:polished_blackstone_brick_slab[type=bottom]"],
              "q":["mekanismgenerators:fusion_reactor_frame"],
              "r":["immersiveengineering:fluid_pipe"],
              "s":["modular_machinery_reborn:fluidinputhatch_vacuum"],
              "t":["glassential:glass_ethereal"],
              "u":["minecraft:water"],
              "v":["minecraft:netherite_block"],
              "w":["minecraft:piston_head[facing=up+short=false+type=normal]"],
              "x":["eternalores:steel_block"],
              "y":["mekanism:ultimate_induction_cell"],
              "A":["eternalores:nethersteel_block"],
              "B":["minecraft:lava"],
              "C":["immersiveengineering:chute_iron[facing=east]"],
              "D":["immersiveengineering:pipe_valve[east=false+north=false+south=false+down=false+up=false+facing=north+west=false]"],
              "E":["immersiveengineering:pipe_valve[east=false+north=false+south=false+down=false+up=false+facing=south+west=false]"],
              "F":["immersiveengineering:pipe_valve[east=false+north=false+south=false+down=false+up=false+facing=east+west=false]"],
              "G":["immersiveengineering:pipe_valve[east=false+north=false+south=false+down=false+up=false+facing=west+west=false]"],
              "H":["modular_machinery_reborn:casing_vent"],
              "I":["minecraft:lava"],
              "J":["minecraft:sticky_piston[extended=false+facing=down]"],
              "K":["minecraft:blue_ice"],
              "L":["minecraft:polished_blackstone_brick_slab[type=top]"],
              "M":["modular_machinery_reborn:casing_plain"],
              "N":["minecraft:iron_block"],
              "O":["mekanism:laser"],
              "P":["mekanism:laser"],
              "Q":["mekanism:laser_amplifier"],
              "R":["mekanism:laser"],
              "S":["mekanismgenerators:laser_focus_matrix"],
              "T":["mekanism:laser"],
              "U":["mekanism:laser_amplifier"],
              "V":["mekanism:laser"],
              "W":["minecraft:lava"],
              "X":["minecraft:chain[axis=y]"],
              "Y":["mekanism:laser"],
              "Z":["minecraft:grindstone"],
              "j":["minecraft:polished_blackstone_wall"]
        }))
});
